### ISSUE TITLE
Printing only OCISharedLibInit call

### ISSUE THREAD

**Issue by AlexShalimov** [kubo/ocidump#1]
Windows 7 x64, Oracle 11.2.0.1 instant client. The dump file is created immediately, but is empty; only one line is written when the traced program exits:

>  5116: OCISharedLibInit(0x9479d40, (nil), 1, 0, (nil), 0x7feec331830 in C:\oracle\instantclient.x64\ocidump.dll) => OCI_SUCCESS

Of course, my program did much more than that. I tried placing fflush in ocidump_log, but it didn't change anything. Checked it with two programs (my own and Toad) — same result. I've copied ocidump.dll into client's folder (where other dlls are located) and added ORA_OCI_UCBPKG=ocidump and OCIDUMP_LOGFILE into env variables; it it enough?

**Comment by kubo** [comment]
Could you check it with sqlplus? I tested it with sqlplus.

Could you change `ocidump.c` as follows and send me the output of your programs?

```
@@ -100,7 +100,7 @@ int ocidump_is_initialized;
 FILE *ocidump_logfp;
 pthread_key_t ocidump_tls_key;

-static unsigned int log_flags = 0;
+static unsigned int log_flags = OCIDUMP_LOG_HOOK;

 static void ocidump_do_init(void)
 {
```

It printed the following log with sqlplus on my environment.

```
# GetProcAddress("OCI.DLL", "OCIAnyDataAccess") => 00007FFA2D842080
# GetProcAddress("OCI.DLL", "OCIAnyDataAttrGet") => 00007FFA2D842138
# GetProcAddress("OCI.DLL", "OCIAnyDataAttrSet") => 00007FFA2D8421FC
# GetProcAddress("OCI.DLL", "OCIAnyDataBeginCreate") => 00007FFA2D8422C0
 ...snip...
# Checking c:\oracle\instantclient_12_1-win64\sqlplus.exe
# Replace OCIErrorGet from 00007FFA2D844FFC to 00007FFA17E71E38.
# Replace OCIDescriptorFree from 00007FFA2D843478 to 00007FFA17E7481D.
# Replace OCIDescriptorAlloc from 00007FFA2D8433E8 to 00007FFA17E743BD.
# Replace OCIDateTimeConvert from 00007FFA2D8561C8 to 00007FFA17E71F4B.
 ...snip...
 6100: OCISharedLibInit(0x961f10, (nil), 1, 0, (nil), 0x7ffa17f31830 in c:\oracle\instantclient_12_1-win64\ocidump.dll) => OCI_SUCCESS
 ...
```

**Comment by AlexShalimov** [comment]
Yes, with sqlplus it works correctly.

It looks like I've found the cause of the problem. Sqlplus links against oci.dll, and because of this oci.dll is in its import directory, and sqldump works well. However, my program and Toad do NOT link against oci.dll, but load it in runtime. So it is not in the import directory, and replace_import_section doesn't processes it.

**Comment by kubo** [comment]
Could you pull the latest source code and try the followings?

``` shell
ruby mkdef.rb C:\oracle\instantclient.x64\oci.dll
nmake -f win32.mak
move C:\oracle\instantclient.x64\oci.dll C:\oracle\instantclient.x64\oci-orig.dll 
copy ocidump.dll C:\oracle\instantclient.x64\oci.dll
```

Your program and Toad load oci.dll whose content is ocidump.dll.
ocidump.dll loads oci-orig.dll. When functions in ocidump.dll are called,
functions in oci-orig.dll are called.
You have no need to add `ORA_OCI_UCBPKG`.

I made `mkdef.rb` ad hoc. There is no error checking in it.

**Comment by AlexShalimov** [comment]
With new source, both Toad and my program are working great; everything is printed as expected.

Found one more bug with printing, will create a separate issue.

**Comment by kubo** [comment]
I committed 7ed3f0eb42c2a53b6cf3028e027189f99cfc8a80.
After it you need to set `OCIDUMP_ENABLE=1` to enable hooks when ocidump.dll is substituted for oci.dll.
See https://github.com/kubo/ocidump#windows-dll-substitution
