### ISSUE TITLE
Crash when trying to print strings with -1 length

### ISSUE THREAD

**Issue by AlexShalimov** [kubo/ocidump#2]
It seems that in most OCI functions, when you pass text and text length, and text is zero-terminated, you can pass -1 as length. For example, in OCIBindByName you can pass -1 as placeh_len (5th parameter), if placeholder is zero-terminated. In this case ocidump crashes trying to print this value. It calls ocidump_string_with_length, and the len parameter for it is unsigned. When you pass -1 for it, it becomes 0xffffffff, which results in access violation later on.

**Comment by kubo** [comment]
Thanks.
IMO, it is an undocumented feature:
In https://docs.oracle.com/database/121/LNOCI/oci16rel003.htm#LNOCI17140

> The length of the name specified in placeholder, in number of bytes regardless of the encoding.

I committed 9d666a40a390f3d1d81128046cc23235338659cd.
Could you try it?

**Comment by AlexShalimov** [comment]
Yes, now it works fine.

Yes, I guess it's undocumented. I've been surprised myself when I've found this in some old code, written long ago by someone else. Don't know how they figured it out.
